dist: xenial
language: go

go:
  - "1.11.x"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev

install:
  - go get github.com/kjx98/golib/to
  - go get github.com/kjx98/go-sdl2/sdl
  - go get github.com/op/go-logging


script:
    - go build rebot/main.go
