tuling:
  url: http://www.tuling123.com/openapi/api
  keys: {
    "test": {name: "gobot", key: "b689c0a4af2f424f8ab3ad6bc323d36e"},
  }

log:
  formatter: "logstash"
  level: info
  writer:
    type: file
    path: wecat.log
